name: CI for test 

on: 
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Build project with Maven
        run: ./mvnw clean install

  test:
    name: Test Job
    runs_on: ubuntu-latest
    needs: build
    setps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Run Tests
        run: ./mvnw test
      